from pathlib import Path
import csv


ROOT = Path(__file__).resolve().parents[1]
SOURCE_PATH = ROOT / "networds.csv"
PATH = ROOT / "networds_expanded.csv"

new_rows = [
    ("Abtastintervall", "采样间隔", "Das Abtastintervall bestimmt den zeitlichen Abstand zweier Proben.（采样间隔决定两次采样之间的时间距离。）"),
    ("Abtastrate", "采样率", "Die Abtastrate gibt an wie oft ein Signal pro Sekunde abgetastet wird.（采样率表示每秒对信号采样多少次。）"),
    ("Abtasttheorem", "采样定理", "Das Abtasttheorem legt die notwendige Abtastrate für ein Signal fest.（采样定理给出信号所需的采样率条件。）"),
    ("Adressauflösung", "地址解析", "Adressauflösung ermittelt zu einer IP-Adresse die passende MAC-Adresse.（地址解析为一个 IP 地址查找对应 MAC 地址。）"),
    ("Adressbereich", "地址范围", "Ein Adressbereich beschreibt eine zusammenhängende Menge von Adressen.（地址范围描述一组连续地址。）"),
    ("Anfrage-Antwort-Dialog", "请求-响应对话", "HTTP folgt häufig einem Anfrage-Antwort-Dialog.（HTTP 常采用请求-响应对话模式。）"),
    ("API", "应用程序接口", "Eine API definiert wie Programme einen Dienst nutzen können.（API 定义程序如何使用某个服务。）"),
    ("ASCII", "美国信息交换标准代码", "ASCII codiert Zeichen als Zahlenwerte.（ASCII 把字符编码为数值。）"),
    ("ASCII-Kodierung", "ASCII 编码", "ASCII-Kodierung wird in Aufgaben zur Byte-Darstellung verwendet.（ASCII 编码常用于字节表示相关练习。）"),
    ("ASN", "自治系统号", "Eine ASN identifiziert ein autonomes System im globalen Routing.（ASN 在全局路由中标识一个自治系统。）"),
    ("Ausbreitungsverzögerung", "传播时延", "Ausbreitungsverzögerung hängt von Entfernung und Ausbreitungsgeschwindigkeit ab.（传播时延取决于距离和传播速度。）"),
    ("BCC", "块校验字符", "BCC ist ein einfaches Verfahren zur Fehlererkennung.（BCC 是一种简单的错误检测方法。）"),
    ("BDP", "带宽时延积", "BDP beschreibt wie viele Daten gleichzeitig im Netz unterwegs sein können.（带宽时延积描述网络中可同时在途的数据量。）"),
    ("Bellman-Ford", "Bellman-Ford 算法", "Bellman-Ford ist eine Grundlage für Distance-Vector-Routing.（Bellman-Ford 是距离向量路由的基础算法。）"),
    ("BER", "比特错误率", "BER misst die Wahrscheinlichkeit fehlerhaft übertragener Bits.（BER 衡量比特传输错误的概率。）"),
    ("big-endian", "大端序", "Bei big-endian steht das höchstwertige Byte zuerst.（大端序中最高有效字节在前。）"),
    ("Binärsystem", "二进制系统", "Das Binärsystem verwendet nur die Ziffern 0 und 1.（二进制系统只使用 0 和 1。）"),
    ("Bit-Zeit", "比特时间", "Eine Bit-Zeit ist die Dauer zur Übertragung eines einzelnen Bits.（比特时间是传输一个比特所需的时间。）"),
    ("Bitrate", "比特率", "Die Bitrate gibt die pro Sekunde übertragenen Bits an.（比特率表示每秒传输的比特数。）"),
    ("Broadcast", "广播", "Broadcast sendet einen Rahmen an alle Stationen im lokalen Netz.（广播把帧发送给本地网络中的所有站点。）"),
    ("BSD Sockets", "BSD 套接字", "BSD Sockets prägten die Programmierschnittstelle für TCP/IP-Kommunikation.（BSD 套接字奠定了 TCP/IP 通信编程接口。）"),
    ("CAT5", "五类双绞线", "CAT5 beschreibt eine Kabelkategorie für Ethernet-Verkabelung.（CAT5 表示以太网布线中的五类线缆类别。）"),
    ("CERN", "欧洲核子研究中心", "Am CERN entstand das World Wide Web.（万维网诞生于 CERN。）"),
    ("Checkbits", "校验位", "Checkbits werden zusätzlich zu Nutzdaten übertragen.（校验位随用户数据一起额外传输。）"),
    ("Classful Network", "有类别网络", "Classful Networks teilen IPv4-Adressen in feste Klassen ein.（有类别网络把 IPv4 地址划分为固定类别。）"),
    ("CLS", "关闭连接控制消息", "CLS kann in einem abstrakten Protokoll die Verbindungsfreigabe markieren.（CLS 可在抽象协议中表示释放连接。）"),
    ("Code-Matrix", "编码矩阵", "Eine Code-Matrix kann gültige und ungültige Codewörter darstellen.（编码矩阵可表示有效和无效码字。）"),
    ("Codewörter", "码字集合", "Codewörter mit größerem Hammingabstand erlauben bessere Fehlererkennung.（汉明距离更大的码字集合有更好的错误检测能力。）"),
    ("Collision Avoidance", "冲突避免", "Collision Avoidance versucht Kollisionen vor dem Senden zu vermeiden.（冲突避免试图在发送前避免冲突。）"),
    ("Collision Detection", "冲突检测", "Collision Detection erkennt eine Kollision während einer laufenden Übertragung.（冲突检测在传输过程中发现冲突。）"),
    ("Congestion-Avoidance-Phase", "拥塞避免阶段", "In der Congestion-Avoidance-Phase wächst das Fenster langsamer.（拥塞避免阶段窗口增长更慢。）"),
    ("Core Router", "核心路由器", "Ein Core Router verarbeitet Verkehr im Kern eines großen Netzes.（核心路由器处理大型网络核心中的流量。）"),
    ("CORBA", "公共对象请求代理体系结构", "CORBA ist ein Beispiel für Middleware in verteilten Systemen.（CORBA 是分布式系统中间件的一个例子。）"),
    ("CPU", "中央处理器", "CPU-Leistung kann die Verarbeitung von Paketen beeinflussen.（CPU 性能会影响分组处理能力。）"),
    ("CTS-Paket", "允许发送分组", "Ein CTS-Paket erlaubt nach einem RTS die Datenübertragung.（CTS 分组在 RTS 后允许进行数据传输。）"),
    ("Data Circuit", "数据电路", "Ein Data Circuit beschreibt im OSI-Kontext eine Datenverbindung.（Data Circuit 在 OSI 语境中描述数据连接。）"),
    ("Data Unit", "数据单元", "Data Unit ist ein Oberbegriff für strukturierte Daten in Schichtenmodellen.（数据单元是分层模型中结构化数据的统称。）"),
    ("Datenrate", "数据率", "Die Datenrate beschreibt die Geschwindigkeit der Datenübertragung.（数据率描述数据传输速度。）"),
    ("Dateneinheit", "数据单元", "Eine Dateneinheit wird je nach Schicht unterschiedlich benannt.（数据单元在不同层有不同名称。）"),
    ("Darstellungsschicht", "表示层", "Die Darstellungsschicht kümmert sich um Kodierung und Datenformate.（表示层负责编码和数据格式。）"),
    ("DCT", "离散余弦变换", "DCT wird bei Quellencodierung und Bildkompression eingesetzt.（DCT 用于信源编码和图像压缩。）"),
    ("DEE", "数据终端设备", "DEE bezeichnet Endgeräte an einer Kommunikationsschnittstelle.（DEE 表示通信接口处的数据终端设备。）"),
    ("DE-NIC", "德国互联网域名注册机构", "DE-NIC verwaltet die deutsche Top-Level-Domain .de.（DE-NIC 管理德国 .de 顶级域。）"),
    ("Dezimalsystem", "十进制系统", "Das Dezimalsystem verwendet zehn Ziffern.（十进制系统使用十个数字。）"),
    ("Dienst", "服务", "Ein Dienst beschreibt was eine Schicht für die darüberliegende Schicht leistet.（服务描述一层为上层提供什么功能。）"),
    ("Dienst-Daten-Einheit", "服务数据单元", "Eine Dienst-Daten-Einheit entspricht der SDU an einer Schnittstelle.（服务数据单元对应接口处的 SDU。）"),
    ("Distanz-Vektor-Algorithmus", "距离向量算法", "Ein Distanz-Vektor-Algorithmus aktualisiert Routen mit Nachbarinformationen.（距离向量算法用邻居信息更新路由。）"),
    ("dotted-decimal", "点分十进制", "IPv4-Adressen werden oft in dotted-decimal notation geschrieben.（IPv4 地址常用点分十进制表示。）"),
    ("DQDB", "分布式队列双总线", "DQDB ist ein Beispiel für ein Zugriffsverfahren in Netzen.（DQDB 是网络访问方法的一个例子。）"),
    ("Drei-Wege-Handschlag", "三次握手", "Der Drei-Wege-Handschlag entspricht dem 3-Way-Handshake.（Drei-Wege-Handschlag 对应三次握手。）"),
    ("Dual-Stack", "双协议栈", "Dual-Stack erlaubt IPv4 und IPv6 parallel auf demselben System.（双协议栈允许同一系统并行使用 IPv4 和 IPv6。）"),
    ("E-Mail", "电子邮件", "E-Mail nutzt Protokolle wie SMTP IMAP oder POP.（电子邮件使用 SMTP、IMAP 或 POP 等协议。）"),
    ("E2E", "端到端", "E2E steht für Ende-zu-Ende.（E2E 表示端到端。）"),
    ("ECN", "显式拥塞通知", "ECN kann Überlast signalisieren ohne Pakete zu verwerfen.（ECN 可在不丢弃分组的情况下显式通知拥塞。）"),
    ("EGP", "外部网关协议", "EGP bezeichnet Routing-Protokolle zwischen autonomen Systemen.（EGP 指自治系统之间的路由协议。）"),
    ("EIA", "电子工业联盟", "EIA ist an Standards für Schnittstellen und Verkabelung beteiligt.（EIA 参与接口和布线标准。）"),
    ("Ende-zu-Ende-Durchsatz", "端到端吞吐量", "Der Ende-zu-Ende-Durchsatz wird oft durch den Bottleneck begrenzt.（端到端吞吐量常由瓶颈链路限制。）"),
    ("Ende-zu-Ende-Prinzip", "端到端原则", "Das Ende-zu-Ende-Prinzip verlagert Funktionen möglichst an die Endsysteme.（端到端原则尽量把功能放到端系统实现。）"),
    ("Ende-zu-Ende-Verbindung", "端到端连接", "TCP stellt eine logische Ende-zu-Ende-Verbindung bereit.（TCP 提供逻辑上的端到端连接。）"),
    ("Entropiecodierung", "熵编码", "Entropiecodierung reduziert Redundanz anhand statistischer Häufigkeiten.（熵编码根据统计频率减少冗余。）"),
    ("Erweiterungs-Header", "扩展头", "IPv6 nutzt Erweiterungs-Header für optionale Zusatzinformationen.（IPv6 使用扩展头携带可选附加信息。）"),
    ("ESTABLISHED", "已建立状态", "ESTABLISHED zeigt bei TCP eine aktive Verbindung an.（ESTABLISHED 表示 TCP 连接已建立。）"),
    ("FDDI", "光纤分布式数据接口", "FDDI ist eine ältere LAN-Technik auf Glasfaserbasis.（FDDI 是一种较早的基于光纤的局域网技术。）"),
    ("FFT", "快速傅里叶变换", "FFT wird zur effizienten Analyse von Frequenzanteilen verwendet.（FFT 用于高效分析频率成分。）"),
    ("Firmennetz", "企业网络", "Ein Firmennetz verbindet Systeme innerhalb einer Organisation.（企业网络连接组织内部的系统。）"),
    ("Flow Control", "流量控制", "Flow Control verhindert dass der Empfänger überlastet wird.（流量控制防止接收方过载。）"),
    ("Flow Label", "流标签", "Das IPv6 Flow Label kann Pakete eines Datenflusses markieren.（IPv6 流标签可标记同一数据流的分组。）"),
    ("Four-Way-Handshake", "四次握手", "Ein Four-Way-Handshake kann für bestimmte Verbindungsfreigaben nötig sein.（某些连接释放过程可能需要四次握手。）"),
    ("Frequenzbereich", "频率范围", "Der Frequenzbereich bestimmt welche Signale über ein Medium nutzbar sind.（频率范围决定介质上可用的信号范围。）"),
    ("Fritz-Box", "Fritz!Box 家用路由器", "Eine Fritz-Box ist ein typischer Router im Heimnetz.（Fritz!Box 是家庭网络中的典型路由器。）"),
    ("Generator-Polynom", "生成多项式", "Ein Generator-Polynom bestimmt die CRC-Berechnung.（生成多项式决定 CRC 的计算方式。）"),
    ("GIOP", "通用ORB间协议", "GIOP gehört zur Kommunikation in CORBA-Systemen.（GIOP 属于 CORBA 系统中的通信协议。）"),
    ("Go-Back-N", "回退 N 协议", "Go-Back-N wiederholt nach einem Verlust mehrere folgende Segmente.（回退 N 协议在丢失后重传多个后续报文段。）"),
    ("Handschlag-Protokoll", "握手协议", "Ein Handschlag-Protokoll synchronisiert Kommunikationspartner.（握手协议用于同步通信双方。）"),
    ("Header Length", "头部长度", "Header Length gibt die Länge eines Protokollheaders an.（头部长度字段表示协议头部长度。）"),
    ("Hexadezimalsystem", "十六进制系统", "Das Hexadezimalsystem wird oft zur kompakten Darstellung von Bytes genutzt.（十六进制常用于紧凑表示字节。）"),
    ("Hop-by-Hop", "逐跳", "Hop-by-Hop-Verarbeitung geschieht an jedem Router entlang des Pfades.（逐跳处理发生在路径上的每台路由器。）"),
    ("HTTP-Request", "HTTP 请求", "Ein HTTP-Request fordert eine Ressource von einem Server an.（HTTP 请求向服务器请求资源。）"),
    ("Hypertext", "超文本", "Hypertext verknüpft Dokumente über Links.（超文本通过链接连接文档。）"),
    ("IETF", "互联网工程任务组", "Die IETF entwickelt und veröffentlicht Internet-Standards.（IETF 制定并发布互联网标准。）"),
    ("IGP", "内部网关协议", "IGP bezeichnet Routing-Protokolle innerhalb eines autonomen Systems.（IGP 指自治系统内部的路由协议。）"),
    ("IHL", "互联网头部长度", "IHL gibt die Länge des IPv4-Headers an.（IHL 表示 IPv4 头部长度。）"),
    ("IMAP", "互联网消息访问协议", "IMAP dient dem Zugriff auf E-Mail-Postfächer.（IMAP 用于访问电子邮件邮箱。）"),
    ("IMP", "接口消息处理机", "Der IMP war ein früher Paketvermittler im ARPANET.（IMP 是 ARPANET 中早期的分组交换设备。）"),
    ("Intra-AS", "自治系统内部", "Intra-AS-Routing findet innerhalb eines autonomen Systems statt.（Intra-AS 路由发生在自治系统内部。）"),
    ("Inter-AS", "自治系统之间", "Inter-AS-Routing verbindet unterschiedliche autonome Systeme.（Inter-AS 路由连接不同自治系统。）"),
    ("Internet Checksumme", "互联网校验和", "Die Internet Checksumme ist ein einfaches Prüfsummenverfahren.（互联网校验和是一种简单的校验方法。）"),
    ("Internet Engineering Task Force", "互联网工程任务组", "Die Internet Engineering Task Force ist als IETF bekannt.（Internet Engineering Task Force 即 IETF。）"),
    ("Internet Header Length", "互联网头部长度", "Internet Header Length bezeichnet das IHL-Feld im IPv4-Header.（Internet Header Length 指 IPv4 头部中的 IHL 字段。）"),
    ("Internet Message Access Protocol", "互联网消息访问协议", "Internet Message Access Protocol ist die ausgeschriebene Form von IMAP.（Internet Message Access Protocol 是 IMAP 的全称。）"),
    ("Internet Protocol Security", "互联网协议安全", "Internet Protocol Security schützt IP-Kommunikation kryptographisch.（IPsec 对 IP 通信提供密码学保护。）"),
    ("Internet Protocol Suite", "互联网协议族", "Die Internet Protocol Suite umfasst Protokolle wie IP TCP und UDP.（互联网协议族包含 IP、TCP、UDP 等协议。）"),
    ("Internet Service Provider", "互联网服务提供商", "Ein Internet Service Provider verbindet Kunden mit dem Internet.（互联网服务提供商把客户接入互联网。）"),
    ("Internet Society", "互联网协会", "Die Internet Society unterstützt offene Entwicklung des Internets.（互联网协会支持互联网的开放发展。）"),
    ("Internet-Anwendungsschicht", "互联网应用层", "Die Internet-Anwendungsschicht umfasst Protokolle wie HTTP und SMTP.（互联网应用层包含 HTTP 和 SMTP 等协议。）"),
    ("Internet-Schichtenmodell", "互联网分层模型", "Das Internet-Schichtenmodell ordnet Protokolle funktionalen Schichten zu.（互联网分层模型把协议按功能划分到各层。）"),
    ("IP-Datagramm", "IP 数据报", "Ein IP-Datagramm trägt Header und Nutzdaten der Vermittlungsschicht.（IP 数据报携带网络层头部和用户数据。）"),
    ("IP-Header", "IP 头部", "Der IP-Header enthält Zieladresse Quelladresse und weitere Steuerfelder.（IP 头部包含源地址、目的地址和其他控制字段。）"),
    ("IP-Paket", "IP 分组", "Ein IP-Paket wird von Routern anhand der Zieladresse weitergeleitet.（IP 分组由路由器根据目的地址转发。）"),
    ("IP-Pseudoheader", "IP 伪头部", "Der IP-Pseudoheader wird bei TCP und UDP in die Prüfsumme einbezogen.（IP 伪头部会参与 TCP 和 UDP 校验和计算。）"),
    ("IPsec", "IP 安全协议", "IPsec kann Authentizität und Vertraulichkeit für IP-Pakete bieten.（IPsec 可为 IP 分组提供认证性和保密性。）"),
    ("ISDN", "综合业务数字网", "ISDN ist eine ältere digitale Zugangstechnik.（ISDN 是较早的数字接入技术。）"),
    ("ISN", "初始序列号", "ISN bezeichnet die initiale Sequenznummer einer TCP-Verbindung.（ISN 表示 TCP 连接的初始序列号。）"),
    ("IT-Sicherheit", "信息技术安全", "IT-Sicherheit ist auch in Netzarchitekturen ein zentrales Thema.（IT 安全也是网络体系结构中的核心议题。）"),
    ("ITU", "国际电信联盟", "Die ITU standardisiert viele Telekommunikationstechniken.（ITU 标准化许多电信技术。）"),
    ("JPEG", "JPEG 图像编码", "JPEG verwendet Transformation und Quantisierung zur Bildkompression.（JPEG 使用变换和量化进行图像压缩。）"),
    ("KISS-Prinzip", "KISS 原则", "Das KISS-Prinzip fordert möglichst einfache Systementwürfe.（KISS 原则要求系统设计尽量简单。）"),
    ("Kollisionsdomäne", "冲突域", "Eine Kollisionsdomäne umfasst Stationen deren Übertragungen kollidieren können.（冲突域包含传输可能互相冲突的站点。）"),
    ("Kommunikations-Middleware", "通信中间件", "Kommunikations-Middleware kapselt Details der Netzkommunikation.（通信中间件封装网络通信细节。）"),
    ("Kommunikationssteuerungsschicht", "通信控制层", "Die Kommunikationssteuerungsschicht entspricht im OSI-Kontext der Sitzungsschicht.（通信控制层在 OSI 语境中对应会话层。）"),
    ("Kosten-Attribut", "代价属性", "Ein Kosten-Attribut bewertet Links in Routing-Algorithmen.（代价属性在路由算法中评价链路。）"),
    ("Kosten-Nutzen-Abwägung", "成本收益权衡", "Zuverlässigkeit erfordert oft eine Kosten-Nutzen-Abwägung.（可靠性通常需要进行成本收益权衡。）"),
    ("Lauflängencodierung", "游程编码", "Lauflängencodierung ersetzt Folgen gleicher Zeichen durch Länge und Wert.（游程编码用长度和值替代连续相同符号。）"),
    ("LED", "发光二极管", "LEDs können als Lichtquellen in Übertragungssystemen dienen.（LED 可作为传输系统中的光源。）"),
    ("Link Adapter", "链路适配器", "Ein Link Adapter verbindet einen Host mit einem Übertragungsmedium.（链路适配器把主机连接到传输介质。）"),
    ("Link Control", "链路控制", "Link Control beschreibt Steuerfunktionen der Sicherungsschicht.（链路控制描述数据链路层的控制功能。）"),
    ("Link-local", "链路本地", "Link-local-Adressen gelten nur auf einem einzelnen Link.（链路本地地址只在单条链路上有效。）"),
    ("Link-State-Routing", "链路状态路由", "Link-State-Routing verteilt Informationen über Linkkosten und Topologie.（链路状态路由传播链路代价和拓扑信息。）"),
    ("LISTEN", "监听状态", "LISTEN zeigt einen Server Socket der auf Verbindungen wartet.（LISTEN 表示服务器套接字正在等待连接。）"),
    ("LLC", "逻辑链路控制", "LLC bildet im OSI-Modell einen Teil der Sicherungsschicht.（LLC 是 OSI 模型中数据链路层的一部分。）"),
    ("LOTOS", "时序逻辑规范语言", "LOTOS kann zur formalen Beschreibung von Protokollen dienen.（LOTOS 可用于协议的形式化描述。）"),
    ("LSP", "链路状态分组", "Ein LSP verteilt Link-State-Informationen im Netz.（LSP 在网络中分发链路状态信息。）"),
    ("LTE", "长期演进移动通信", "LTE verbindet mobile Endsysteme mit dem Internet.（LTE 把移动端系统连接到互联网。）"),
    ("LWL", "光纤", "LWL ist die Abkürzung für Lichtwellenleiter.（LWL 是光纤的德语缩写。）"),
    ("MAC-Feld", "MAC 字段", "MAC-Felder enthalten Quell- und Zieladressen im Ethernet-Rahmen.（MAC 字段包含以太网帧中的源和目的地址。）"),
    ("MAC-Port-Paar", "MAC-端口对", "Ein Switch lernt MAC-Port-Paare aus empfangenen Rahmen.（交换机从收到的帧中学习 MAC-端口对。）"),
    ("man-Page", "手册页", "Eine man-Page dokumentiert Befehle wie ping oder traceroute.（man 手册页记录 ping 或 traceroute 等命令。）"),
    ("Media Access Control", "介质访问控制", "Media Access Control ist die ausgeschriebene Form von MAC.（Media Access Control 是 MAC 的全称。）"),
    ("Message Sequence Chart", "消息序列图", "Ein Message Sequence Chart beschreibt Nachrichten über die Zeit.（消息序列图按时间描述消息交互。）"),
    ("MPEG", "动态图像专家组编码", "MPEG-Standards beschreiben Verfahren zur Video- und Audiokompression.（MPEG 标准描述视频和音频压缩方法。）"),
    ("MSL", "报文最大生存期", "MSL begrenzt wie lange alte Segmente im Netz bleiben können.（MSL 限制旧报文段在网络中可能存在的最长时间。）"),
    ("Multicast", "组播", "Multicast adressiert eine Gruppe von Empfängern.（组播面向一组接收方寻址。）"),
    ("Multicast-Adresse", "组播地址", "Eine Multicast-Adresse identifiziert eine Empfängergruppe.（组播地址标识一个接收方组。）"),
    ("N-ICI", "N 层接口控制信息", "N-ICI bezeichnet Schnittstellenkontrollinformation auf Schicht N.（N-ICI 表示第 N 层接口控制信息。）"),
    ("N-IDU", "N 层接口数据单元", "N-IDU besteht aus N-ICI und N-ID an einer Schichtgrenze.（N-IDU 由层边界处的 N-ICI 和 N-ID 组成。）"),
    ("N-PDU", "N 层协议数据单元", "Eine N-PDU ist die Protokolldateneinheit der Schicht N.（N-PDU 是第 N 层协议数据单元。）"),
    ("N-SDU", "N 层服务数据单元", "Eine N-SDU wird von einer höheren Schicht an Schicht N übergeben.（N-SDU 由上层交给第 N 层处理。）"),
    ("NAK", "否认确认", "NAK signalisiert dass eine Nachricht nicht korrekt empfangen wurde.（NAK 表示消息未被正确接收。）"),
    ("Nachbarknoten", "邻居节点", "Routingverfahren tauschen Informationen oft mit Nachbarknoten aus.（路由方法常与邻居节点交换信息。）"),
    ("Nachrichtenvermittlung", "报文交换", "Nachrichtenvermittlung speichert ganze Nachrichten vor dem Weiterleiten.（报文交换在转发前存储整条消息。）"),
    ("NCP", "网络控制协议", "NCP war ein frühes Protokoll im ARPANET.（NCP 是 ARPANET 早期协议。）"),
    ("Network Address Translation", "网络地址转换", "Network Address Translation ist die ausgeschriebene Form von NAT.（Network Address Translation 是 NAT 的全称。）"),
    ("Network Control Protocol", "网络控制协议", "Network Control Protocol bezeichnet NCP im historischen ARPANET-Kontext.（Network Control Protocol 指历史 ARPANET 语境中的 NCP。）"),
    ("Network Working Group", "网络工作组", "Die Network Working Group erstellte frühe Internet-Protokolldokumente.（Network Working Group 编写了早期互联网协议文档。）"),
    ("NIC", "网络接口卡", "NIC steht für Network Interface Card.（NIC 表示网络接口卡。）"),
    ("NRZ", "不归零编码", "NRZ ist ein einfaches Leitungscodierungsverfahren.（NRZ 是一种简单的线路编码方法。）"),
    ("NTP", "网络时间协议", "NTP synchronisiert Uhren über ein Netzwerk.（NTP 通过网络同步时钟。）"),
    ("Oktalsystem", "八进制系统", "Das Oktalsystem verwendet die Ziffern 0 bis 7.（八进制系统使用数字 0 到 7。）"),
    ("Open Shortest Path First", "开放式最短路径优先", "Open Shortest Path First ist die ausgeschriebene Form von OSPF.（Open Shortest Path First 是 OSPF 的全称。）"),
    ("Open System Interconnection", "开放系统互连", "Open System Interconnection ist die ausgeschriebene Bedeutung von OSI.（Open System Interconnection 是 OSI 的全称含义。）"),
    ("Options-Feld", "选项字段", "Das Options-Feld kann zusätzliche TCP-Informationen enthalten.（选项字段可包含额外 TCP 信息。）"),
    ("OSI-Modell", "OSI 模型", "Das OSI-Modell strukturiert Kommunikation in sieben Schichten.（OSI 模型把通信划分为七层。）"),
    ("OSI-Schichtenmodell", "OSI 分层模型", "Das OSI-Schichtenmodell trennt Dienste Protokolle und Schnittstellen.（OSI 分层模型区分服务、协议和接口。）"),
    ("OSPF", "开放式最短路径优先协议", "OSPF ist ein Link-State-Protokoll innerhalb autonomer Systeme.（OSPF 是自治系统内部的链路状态协议。）"),
    ("Packet Loss", "分组丢失", "Packet Loss kann TCP zur Verringerung der Senderate veranlassen.（分组丢失可能促使 TCP 降低发送速率。）"),
    ("Paritätsmatrix", "奇偶校验矩阵", "Eine Paritätsmatrix kann mehrere Bitfehler besser lokalisieren.（奇偶校验矩阵能更好定位多个比特错误。）"),
    ("PAWS", "防止序列号回绕机制", "PAWS nutzt Zeitstempel um alte TCP-Segmente zu erkennen.（PAWS 使用时间戳识别旧 TCP 报文段。）"),
    ("PCM", "脉冲编码调制", "PCM tastet analoge Signale ab und quantisiert sie digital.（PCM 对模拟信号采样并数字量化。）"),
    ("Peer-Entität", "对等实体", "Eine Peer-Entität kommuniziert logisch mit einer Instanz derselben Schicht.（对等实体与同层实例进行逻辑通信。）"),
    ("Petri-Netz", "Petri 网", "Petri-Netze können Abläufe in Protokollen modellieren.（Petri 网可建模协议流程。）"),
    ("PHY", "物理层实体", "PHY bezeichnet die physikalische Schicht oder deren Implementierung.（PHY 表示物理层或其实现。）"),
    ("Pin-Belegung", "引脚分配", "Pin-Belegung beschreibt die Funktion einzelner Kontakte einer Schnittstelle.（引脚分配描述接口各触点的功能。）"),
    ("POP", "邮局协议", "POP ist ein Protokoll zum Abrufen von E-Mails.（POP 是用于收取电子邮件的协议。）"),
    ("Port-Steuer-Info", "端口控制信息", "Port-Steuer-Info kann einen Dienstzugriff näher bestimmen.（端口控制信息可进一步确定服务访问。）"),
    ("PPP", "点对点协议", "PPP wird für Punkt-zu-Punkt-Verbindungen auf der Netzanschlussschicht genutzt.（PPP 用于网络接入层的点对点连接。）"),
    ("Prädiktion", "预测编码", "Prädiktion kann bei Quellencodierung Redundanz reduzieren.（预测可在信源编码中减少冗余。）"),
    ("Präfix-Notation", "前缀表示法", "CIDR nutzt Präfix-Notation wie 192.168.0.0/24.（CIDR 使用 192.168.0.0/24 这样的前缀表示法。）"),
    ("Presentation Layer", "表示层", "Presentation Layer ist die englische Bezeichnung der OSI-Darstellungsschicht.（Presentation Layer 是 OSI 表示层的英文名称。）"),
    ("Protocol-Spalte", "协议列", "Die Protocol-Spalte in Wireshark zeigt den erkannten Protokolltyp.（Wireshark 的协议列显示识别出的协议类型。）"),
    ("Protokoll-Dateneinheit", "协议数据单元", "Protokoll-Dateneinheit ist die deutsche Langform von PDU.（Protokoll-Dateneinheit 是 PDU 的德语全称。）"),
    ("Protokoll-Steuer-Information", "协议控制信息", "Protokoll-Steuer-Information ist die deutsche Langform von PCI.（Protokoll-Steuer-Information 是 PCI 的德语全称。）"),
    ("PSH", "TCP 推送标志", "PSH fordert eine zügige Weitergabe der Daten an die Anwendung.（PSH 要求尽快把数据交给应用。）"),
    ("PSK", "相移键控", "PSK moduliert Information über die Phase eines Trägersignals.（PSK 通过载波相位调制信息。）"),
    ("Punkt-zu-Punkt", "点对点", "Punkt-zu-Punkt beschreibt eine Verbindung zwischen genau zwei Endpunkten.（点对点描述两个端点之间的连接。）"),
    ("QSB", "源汇树", "Ein QSB beschreibt Wege von einer Quelle zu mehreren Senken.（QSB 描述从一个源到多个汇点的路径树。）"),
    ("QUIC", "快速 UDP 互联网连接协议", "QUIC realisiert Transportfunktionen auf Basis von UDP.（QUIC 基于 UDP 实现传输层功能。）"),
    ("Quell-MAC-Adresse", "源 MAC 地址", "Die Quell-MAC-Adresse steht im Ethernet-Rahmen.（源 MAC 地址位于以太网帧中。）"),
    ("Quellencodierung", "信源编码", "Quellencodierung entfernt Redundanz aus den zu übertragenden Daten.（信源编码去除待传输数据中的冗余。）"),
    ("RAM", "随机存取存储器", "RAM kann als Puffer für Pakete und Rahmen dienen.（RAM 可作为分组和帧的缓冲区。）"),
    ("Rechnernetzwerk", "计算机网络", "Rechnernetzwerk wird oft synonym zu Rechnernetz verwendet.（Rechnernetzwerk 常与 Rechnernetz 同义使用。）"),
    ("Referenzmodell", "参考模型", "Ein Referenzmodell hilft beim strukturierten Vergleich von Protokollarchitekturen.（参考模型帮助结构化比较协议体系结构。）"),
    ("REST", "表述性状态转移", "REST beschreibt einen Architekturstil für Web-APIs.（REST 描述 Web API 的一种架构风格。）"),
    ("Restfehlerrate", "残余错误率", "Die Restfehlerrate bleibt nach Fehlererkennung oder Korrektur übrig.（残余错误率是在错误检测或纠正后仍剩下的错误概率。）"),
    ("RIB", "路由信息库", "RIB ist die Abkürzung für Routing Information Base.（RIB 是 Routing Information Base 的缩写。）"),
    ("RIP", "路由信息协议", "RIP ist ein Distance-Vector-Routing-Protokoll.（RIP 是距离向量路由协议。）"),
    ("RLE", "游程编码", "RLE ist die Abkürzung für Run Length Encoding.（RLE 是游程编码的缩写。）"),
    ("Routing-Protokoll", "路由协议", "Ein Routing-Protokoll tauscht Informationen zur Pfadwahl aus.（路由协议交换用于路径选择的信息。）"),
    ("Routing-Tabelle", "路由表", "Eine Routing-Tabelle enthält Ziele und passende nächste Hops.（路由表包含目标以及对应下一跳。）"),
    ("Routingverfahren", "路由方法", "Routingverfahren bestimmen wie Pfade berechnet und aktualisiert werden.（路由方法决定路径如何计算和更新。）"),
    ("RPC", "远程过程调用", "RPC ruft Funktionen auf entfernten Systemen auf.（RPC 调用远程系统上的函数。）"),
    ("RST", "TCP 重置标志", "RST kann eine TCP-Verbindung abrupt zurücksetzen.（RST 可突然重置 TCP 连接。）"),
    ("RTS-Paket", "请求发送分组", "Ein RTS-Paket reserviert bei MACA konzeptionell das Medium.（RTS 分组在 MACA 中概念上预留介质。）"),
    ("RTT", "往返时间", "RTT ist eine gebräuchliche englische Bezeichnung für Round Trip Time.（RTT 是往返时间的常用英文缩写。）"),
    ("Run Length Encoding", "游程编码", "Run Length Encoding komprimiert Folgen gleicher Symbole.（游程编码压缩连续相同符号。）"),
    ("SAP-Adresse", "服务访问点地址", "Eine SAP-Adresse identifiziert einen Dienstzugangspunkt.（SAP 地址标识服务访问点。）"),
    ("Schiebefensterprotokoll", "滑动窗口协议", "Ein Schiebefensterprotokoll erlaubt mehrere unbestätigte Segmente.（滑动窗口协议允许多个未确认报文段在途。）"),
    ("Schnittstellen-Daten", "接口数据", "Schnittstellen-Daten werden zusammen mit Steuerdaten übergeben.（接口数据与控制数据一起在层间传递。）"),
    ("Schnittstellen-Steuerdaten", "接口控制数据", "Schnittstellen-Steuerdaten steuern den Dienstzugriff zwischen Schichten.（接口控制数据控制层间服务访问。）"),
    ("SDMA", "空分多址", "SDMA trennt Kommunikation räumlich über verschiedene Bereiche.（SDMA 通过空间区域区分通信。）"),
    ("SEND", "发送原语", "SEND kann als Dienstprimitive zum Absenden von Daten dienen.（SEND 可作为发送数据的服务原语。）"),
    ("Service Access Point", "服务访问点", "Service Access Point ist die englische Langform von SAP.（Service Access Point 是 SAP 的英文全称。）"),
    ("Service Data Unit", "服务数据单元", "Service Data Unit ist die englische Langform von SDU.（Service Data Unit 是 SDU 的英文全称。）"),
    ("Session Layer", "会话层", "Session Layer ist die englische Bezeichnung der OSI-Sitzungsschicht.（Session Layer 是 OSI 会话层的英文名称。）"),
    ("Sicherungsschicht", "数据链路层", "Die Sicherungsschicht überträgt Rahmen zwischen benachbarten Knoten.（数据链路层在相邻节点之间传输帧。）"),
    ("Signalverzögerung", "信号传播时延", "Signalverzögerung entsteht durch die endliche Ausbreitungsgeschwindigkeit.（信号传播时延来自有限的传播速度。）"),
    ("Site-local", "站点本地", "Site-local-Adressen waren für lokale IPv6-Standorte gedacht.（站点本地地址曾用于 IPv6 本地站点范围。）"),
    ("Sitzungsschicht", "会话层", "Die Sitzungsschicht verwaltet Sitzungen zwischen Kommunikationspartnern.（会话层管理通信伙伴之间的会话。）"),
    ("SLAAC", "无状态地址自动配置", "SLAAC ermöglicht IPv6-Hosts automatische Adresskonfiguration.（SLAAC 允许 IPv6 主机自动配置地址。）"),
    ("Sliding Window", "滑动窗口", "Sliding Window verbessert Durchsatz gegenüber Stop-and-Wait.（滑动窗口相比停止等待能提高吞吐量。）"),
    ("Slow-Start-Phase", "慢启动阶段", "In der Slow-Start-Phase wächst CongWin exponentiell.（慢启动阶段中拥塞窗口指数增长。）"),
    ("SNAP", "子网接入协议", "SNAP erscheint in OSI-nahen Beschreibungen von Netzschnittstellen.（SNAP 出现在偏 OSI 的网络接口描述中。）"),
    ("Socket-Paar", "套接字对", "Eine TCP-Verbindung wird durch ein Paar von Sockets beschrieben.（TCP 连接由一对套接字描述。）"),
    ("Software-Defined", "软件定义", "Software-Defined Networking trennt Steuerung und Weiterleitung.（软件定义网络分离控制与转发。）"),
    ("SPF", "最短路径优先", "SPF berechnet Pfade mit minimalen Kosten.（SPF 计算最小代价路径。）"),
    ("SPF-Algorithmus", "最短路径优先算法", "Der SPF-Algorithmus wird in Link-State-Routing verwendet.（SPF 算法用于链路状态路由。）"),
    ("SSH", "安全外壳协议", "SSH ermöglicht verschlüsselte entfernte Anmeldung.（SSH 支持加密的远程登录。）"),
    ("Staufenster", "拥塞窗口", "Staufenster ist eine deutsche Bezeichnung für Congestion Window.（Staufenster 是拥塞窗口的德语说法。）"),
    ("Staukontrolle", "拥塞控制", "Staukontrolle reduziert die Senderate bei Überlast im Netz.（拥塞控制在网络过载时降低发送速率。）"),
    ("Stellenwertsystem", "位置记数制", "Ein Stellenwertsystem bewertet Ziffern nach ihrer Position.（位置记数制按数字位置赋予权值。）"),
    ("STP", "屏蔽双绞线", "STP bezeichnet geschirmte Twisted-Pair-Kabel.（STP 表示屏蔽双绞线。）"),
    ("Subnetz-Adresse", "子网地址", "Eine Subnetz-Adresse identifiziert ein bestimmtes Subnetz.（子网地址标识一个具体子网。）"),
    ("Subnetzmaske", "子网掩码", "Eine Subnetzmaske trennt Netzanteil und Hostanteil einer Adresse.（子网掩码区分地址中的网络部分和主机部分。）"),
    ("SYN-ACK", "同步确认", "SYN-ACK ist eine verbreitete Schreibweise für SYN+ACK.（SYN-ACK 是 SYN+ACK 的常见写法。）"),
    ("Systemschnitt", "系统接口边界", "Ein Systemschnitt trennt reale Kommunikationssysteme voneinander.（系统接口边界把真实通信系统彼此分开。）"),
    ("TCP-PCI", "TCP 协议控制信息", "TCP-PCI enthält Flags Sequenznummern und weitere Steuerfelder.（TCP-PCI 包含标志、序列号等控制字段。）"),
    ("TCP-PDU", "TCP 协议数据单元", "Eine TCP-PDU wird im Kurs als Segment bezeichnet.（TCP-PDU 在课程中称为报文段。）"),
    ("TCP-Socket", "TCP 套接字", "Ein TCP-Socket stellt eine streamorientierte Verbindung bereit.（TCP 套接字提供面向流的连接。）"),
    ("TCP-Verbindung", "TCP 连接", "Eine TCP-Verbindung besteht logisch zwischen zwei Socket-Endpunkten.（TCP 连接在逻辑上存在于两个套接字端点之间。）"),
    ("TDMA", "时分多址", "TDMA teilt ein Medium in zeitliche Slots auf.（TDMA 将介质划分为时间槽。）"),
    ("TFTP", "简单文件传输协议", "TFTP nutzt UDP für einfache Dateiübertragung.（TFTP 使用 UDP 进行简单文件传输。）"),
    ("TIA", "电信工业协会", "TIA ist an Standards für Telekommunikationsverkabelung beteiligt.（TIA 参与电信布线标准。）"),
    ("Timestamp-Option", "时间戳选项", "Die Timestamp-Option hilft TCP bei Messung und PAWS.（时间戳选项帮助 TCP 进行测量和 PAWS 判断。）"),
    ("Top-Down-Ansatz", "自顶向下方法", "Der Top-Down-Ansatz beginnt bei Anwendungen und geht zu unteren Schichten.（自顶向下方法从应用层出发再到下层。）"),
    ("Topologie", "拓扑", "Topologie beschreibt die Struktur von Knoten und Links.（拓扑描述节点和链路的结构。）"),
    ("TOR", "洋葱路由网络", "TOR leitet Verkehr über mehrere Knoten zur Anonymisierung.（TOR 通过多个节点转发流量以实现匿名化。）"),
    ("Trace-Datei", "抓包记录文件", "Eine Trace-Datei enthält aufgezeichneten Netzwerkverkehr.（抓包记录文件包含被捕获的网络流量。）"),
    ("Transformation", "变换编码", "Transformation wird bei Quellencodierung wie JPEG eingesetzt.（变换编码用于 JPEG 等信源编码。）"),
    ("Transitknoten", "中转节点", "Transitknoten leiten Pakete weiter ohne Endziel zu sein.（中转节点不是最终目的地，只负责转发分组。）"),
    ("Transitsystem", "传输/中转系统", "Ein Transitsystem liegt zwischen sendendem und empfangendem Endsystem.（中转系统位于发送端系统和接收端系统之间。）"),
    ("Transportprotokoll", "传输协议", "TCP und UDP sind Transportprotokolle.（TCP 和 UDP 是传输协议。）"),
    ("Twisted-Pair-Kabel", "双绞线", "Twisted-Pair-Kabel werden häufig für Ethernet verwendet.（双绞线常用于以太网。）"),
    ("UDP-Datagramm", "UDP 数据报", "Ein UDP-Datagramm enthält Ports Länge Prüfsumme und Nutzdaten.（UDP 数据报包含端口、长度、校验和和用户数据。）"),
    ("UDP-Socket", "UDP 套接字", "Ein UDP-Socket sendet und empfängt einzelne Datagramme.（UDP 套接字发送和接收独立数据报。）"),
    ("Unicast", "单播", "Unicast adressiert genau einen Empfänger.（单播寻址一个唯一接收方。）"),
    ("Unicast-Adresse", "单播地址", "Eine Unicast-Adresse steht für genau eine Schnittstelle.（单播地址表示一个特定接口。）"),
    ("URG", "TCP 紧急标志", "URG markiert dringende Daten im TCP-Header.（URG 在 TCP 头部标记紧急数据。）"),
    ("URL", "统一资源定位符", "Eine URL beschreibt Zugriffsmethode und Ort einer Ressource.（URL 描述资源的访问方法和位置。）"),
    ("Vermittlungsverfahren", "交换方式", "Vermittlungsverfahren beschreiben wie Daten durch ein Netz transportiert werden.（交换方式描述数据如何穿过网络。）"),
    ("Verteiltes Dateisystem", "分布式文件系统", "Ein verteiltes Dateisystem speichert Daten über mehrere Rechner hinweg.（分布式文件系统把数据存储在多台计算机上。）"),
    ("Verzerrung", "失真", "Verzerrung verändert die Form eines Signals während der Übertragung.（失真会在传输过程中改变信号形状。）"),
    ("Vier-Tupel", "四元组", "Ein Vier-Tupel aus IP-Adressen und Ports identifiziert eine Verbindung.（由 IP 地址和端口组成的四元组标识一条连接。）"),
    ("Vier-Wege-Handshake", "四次握手", "Ein Vier-Wege-Handshake kann Verbindungsabbau in beide Richtungen bestätigen.（四次握手可确认双向连接释放。）"),
    ("Vielfachzugriff", "多路访问", "Vielfachzugriff regelt mehrere Sender auf einem gemeinsamen Medium.（多路访问规定多个发送方如何共享介质。）"),
    ("Virtuelle Verbindung", "虚连接", "Eine virtuelle Verbindung abstrahiert die darunterliegenden Netze.（虚连接抽象掉底层网络细节。）"),
    ("VLAN-Protocol-ID", "VLAN 协议标识", "Die VLAN-Protocol-ID kennzeichnet VLAN-getaggte Ethernet-Rahmen.（VLAN 协议标识标记带 VLAN 标签的以太网帧。）"),
    ("VoIP", "网络语音", "VoIP überträgt Sprachdaten über IP-Netze.（VoIP 通过 IP 网络传输语音数据。）"),
    ("Vollduplex", "全双工", "Vollduplex erlaubt gleichzeitiges Senden und Empfangen.（全双工允许同时发送和接收。）"),
    ("WAN", "广域网", "Ein WAN verbindet Netze über große räumliche Entfernungen.（广域网跨较大地理距离连接网络。）"),
    ("Weg-Zeit-Diagramm", "路径-时间图", "Ein Weg-Zeit-Diagramm visualisiert Nachrichtenbewegung über die Zeit.（路径-时间图展示消息随时间的移动。）"),
    ("Wege-Handschlag", "二/三路握手", "Wege-Handschlag bezeichnet Handshake-Verfahren mit mehreren Nachrichten.（Wege-Handschlag 指由多条消息组成的握手过程。）"),
    ("WiFi-Adapter", "WiFi 适配器", "Ein WiFi-Adapter verbindet ein Endsystem drahtlos mit einem WLAN.（WiFi 适配器把端系统无线连接到 WLAN。）"),
    ("Wraparound", "序列号回绕", "Wraparound entsteht wenn ein begrenzter Sequenznummernraum wieder von vorn beginnt.（序列号空间有限时重新从头使用会产生回绕。）"),
    ("XCP", "显式控制协议", "XCP ist ein Ansatz für explizite Überlastkontrolle.（XCP 是显式拥塞控制的一种方法。）"),
    ("XOR", "异或", "XOR wird in vielen Prüf- und Codierungsverfahren verwendet.（异或用于许多校验和编码方法。）"),
    ("Zieladresse", "目的地址", "Die Zieladresse entscheidet wohin ein Paket weitergeleitet wird.（目的地址决定分组被转发到哪里。）"),
    ("Zwei-Wege-Handschlag", "二次握手", "Der Zwei-Wege-Handschlag reicht in unzuverlässigen Netzen oft nicht aus.（二次握手在不可靠网络中通常不够。）"),
]

extra_rows = [
    ("Abgabe", "提交/交作业", "Die Abgabe erfolgt häufig über Moodle oder ein Übungssystem.（作业提交通常通过 Moodle 或练习系统完成。）"),
    ("Ablauf", "流程/执行过程", "Der Ablauf eines Protokolls kann mit einem Diagramm beschrieben werden.（协议流程可以用图表示。）"),
    ("Anforderung", "要求/需求", "Anforderungen an ein Netz betreffen Zuverlässigkeit Durchsatz und Skalierbarkeit.（网络需求涉及可靠性、吞吐量和可扩展性。）"),
    ("Aufbau", "结构/建立过程", "Der Aufbau eines Ethernet-Rahmens enthält Präambel Adressen Typ und Prüfsumme.（以太网帧结构包含前导码、地址、类型和校验和。）"),
    ("Bewertung", "评价/评估", "Die Bewertung eines Protokolls betrachtet Effizienz Zuverlässigkeit und Overhead.（协议评估会考察效率、可靠性和开销。）"),
    ("Begegnung", "应对/处理", "Maßnahmen zur Begegnung von IPv4-Adressknappheit sind NAT CIDR und IPv6.（应对 IPv4 地址短缺的措施包括 NAT、CIDR 和 IPv6。）"),
    ("Begründen", "说明理由/论证", "Begründen Sie die Wahl eines Routingverfahrens anhand der Anforderungen.（请根据需求说明选择某种路由方法的理由。）"),
    ("Berechnen", "计算", "Berechnen Sie den Round Trip Delay aus den beobachteten Paketen.（请根据观察到的分组计算往返时延。）"),
    ("Bestimmen", "确定/求出", "Bestimmen Sie die passende Subnetzmaske für den gegebenen Adressbereich.（请确定给定地址范围的合适子网掩码。）"),
    ("Darstellung", "表示/表达形式", "Die Darstellung einer Adresse kann binär dezimal oder hexadezimal erfolgen.（地址可以用二进制、十进制或十六进制表示。）"),
    ("Eigenschaft", "性质/特性", "Eine wichtige Eigenschaft von TCP ist zuverlässige Übertragung.（TCP 的重要特性之一是可靠传输。）"),
    ("Einführung", "导论/引入", "Die Einführung erklärt zuerst Motivation und Grundbegriffe.（导论先解释动机和基本概念。）"),
    ("Ermitteln", "求出/确定", "Ermitteln Sie die MAC-Adresse mithilfe einer ARP-Anfrage.（请借助 ARP 请求确定 MAC 地址。）"),
    ("Erläutern", "解释/阐明", "Erläutern Sie den Unterschied zwischen verbindungsloser und verbindungsorientierter Kommunikation.（请解释无连接通信和面向连接通信的区别。）"),
    ("Gegensatz", "相反/对比", "Im Gegensatz zu TCP ist UDP verbindungslos.（与 TCP 相比，UDP 是无连接的。）"),
    ("Grundlagen", "基础", "Die Grundlagen behandeln Schichten Dienste Schnittstellen und Protokolle.（基础部分讨论层、服务、接口和协议。）"),
    ("Hintergrund", "背景", "Der technische Hintergrund erklärt warum IPv4-Adressen knapp wurden.（技术背景解释了为什么 IPv4 地址变得紧缺。）"),
    ("Hintergründe", "背景资料/来龙去脉", "TOR-Hintergründe helfen die Motivation und Funktionsweise zu verstehen.（TOR 的背景资料有助于理解其动机和工作方式。）"),
    ("Hinweis", "提示", "Ein Hinweis kann eine Annahme für die Berechnung festlegen.（提示可能给出计算所需的假设。）"),
    ("Identifizieren", "识别/找出", "Identifizieren Sie die Segmente die zum Verbindungsabbau gehören.（请识别属于连接释放过程的报文段。）"),
    ("Konzeption", "构想/设计思路", "Die Konzeption eines Protokolls legt Nachrichten und Zustände fest.（协议构想会规定消息和状态。）"),
    ("Konzeptionelle Sicht", "概念视角", "Die konzeptionelle Sicht zeigt MACA ohne Implementierungsdetails.（概念视角展示 MACA，而不涉及实现细节。）"),
    ("Maßnahme", "措施", "Eine Maßnahme gegen Adressknappheit ist Network Address Translation.（应对地址短缺的一项措施是网络地址转换。）"),
    ("Motivation", "动机", "Die Motivation erklärt warum Rechnernetze und verteilte Systeme wichtig sind.（动机部分解释为什么计算机网络与分布式系统重要。）"),
    ("Organisatorisches", "课程组织事项", "Organisatorisches umfasst Moodle Übungen Abgabe und Klausurinformationen.（课程组织事项包括 Moodle、习题、提交和考试信息。）"),
    ("Sichtweise", "视角/观点", "Je nach Sichtweise kann ein System Rechnernetz oder verteiltes System sein.（根据视角不同，一个系统可能是计算机网络或分布式系统。）"),
    ("Skizzieren", "草画/概述", "Skizzieren Sie ein Zustandsdiagramm für den Drei-Wege-Handschlag.（请画出三次握手的状态图草图。）"),
    ("Unterschied", "区别", "Der Unterschied zwischen Dienst und Protokoll ist im Schichtenmodell zentral.（服务和协议之间的区别在分层模型中很关键。）"),
    ("Vergleichen", "比较", "Vergleichen Sie Paketvermittlung und Leitungsvermittlung.（请比较分组交换和电路交换。）"),
    ("Zeichnen", "绘制", "Zeichnen Sie ein Sequenzdiagramm des TCP-Austausches.（请绘制 TCP 交换的序列图。）"),
    ("Zusammenfassung", "总结", "Die Zusammenfassung wiederholt die wichtigsten Begriffe eines Kapitels.（总结部分回顾一章中的重要概念。）"),
]


with SOURCE_PATH.open("r", encoding="utf-8", newline="") as handle:
    rows = [tuple(row) for row in csv.reader(handle) if row]

merged = {row[0]: row for row in rows}
for row in new_rows + extra_rows:
    merged.setdefault(row[0], row)

sorted_rows = sorted(merged.values(), key=lambda row: row[0].casefold())

with PATH.open("w", encoding="utf-8", newline="") as handle:
    writer = csv.writer(handle)
    writer.writerows(sorted_rows)

print(f"old_rows={len(rows)}")
print(f"added={len(sorted_rows) - len(rows)}")
print(f"new_rows={len(sorted_rows)}")
